/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutWalletRouteImport } from './routes/_layout/wallet'
import { Route as LayoutHomeRouteImport } from './routes/_layout/home'
import { Route as LayoutBetHistoryRouteImport } from './routes/_layout/bet-history'
import { Route as LayoutGamesMonkeyCrashRouteImport } from './routes/_layout/games/monkey-crash'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWalletRoute = LayoutWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBetHistoryRoute = LayoutBetHistoryRouteImport.update({
  id: '/bet-history',
  path: '/bet-history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGamesMonkeyCrashRoute = LayoutGamesMonkeyCrashRouteImport.update({
  id: '/games/monkey-crash',
  path: '/games/monkey-crash',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bet-history': typeof LayoutBetHistoryRoute
  '/home': typeof LayoutHomeRoute
  '/wallet': typeof LayoutWalletRoute
  '/games/monkey-crash': typeof LayoutGamesMonkeyCrashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bet-history': typeof LayoutBetHistoryRoute
  '/home': typeof LayoutHomeRoute
  '/wallet': typeof LayoutWalletRoute
  '/games/monkey-crash': typeof LayoutGamesMonkeyCrashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/bet-history': typeof LayoutBetHistoryRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/wallet': typeof LayoutWalletRoute
  '/_layout/games/monkey-crash': typeof LayoutGamesMonkeyCrashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bet-history'
    | '/home'
    | '/wallet'
    | '/games/monkey-crash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bet-history'
    | '/home'
    | '/wallet'
    | '/games/monkey-crash'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/bet-history'
    | '/_layout/home'
    | '/_layout/wallet'
    | '/_layout/games/monkey-crash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/wallet': {
      id: '/_layout/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof LayoutWalletRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bet-history': {
      id: '/_layout/bet-history'
      path: '/bet-history'
      fullPath: '/bet-history'
      preLoaderRoute: typeof LayoutBetHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/games/monkey-crash': {
      id: '/_layout/games/monkey-crash'
      path: '/games/monkey-crash'
      fullPath: '/games/monkey-crash'
      preLoaderRoute: typeof LayoutGamesMonkeyCrashRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBetHistoryRoute: typeof LayoutBetHistoryRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutWalletRoute: typeof LayoutWalletRoute
  LayoutGamesMonkeyCrashRoute: typeof LayoutGamesMonkeyCrashRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBetHistoryRoute: LayoutBetHistoryRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutWalletRoute: LayoutWalletRoute,
  LayoutGamesMonkeyCrashRoute: LayoutGamesMonkeyCrashRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
